name: Docker Image CI

env:
  REGISTRY: papanango33/groupe_4
  IMAGE_NAME: ${{github.repository}}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{env.REGISTRY}}:latest

      - name: Log into registry ${{env.REGISTRY}}
        run: docker lohin -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push Docker image
        run: docker push ${{env.REGISTRY}}:latest
